name: PIG
version: 72
author: Zach_FR
main: pig.Main
description: ÀPIGGGGGGGGGGGGGGGGGGGdudnydfhfydfb7afy

commands:
  pig:
    description: fwuofyfga7aig67g32fyshewyagftgfyudsbftweygfsyaoygcegfetysudy

  createpig:
    description: create pig